# Generated by Django 5.0 on 2023-12-20 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='created_at',
        ),
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='posts',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
