# Generated by Django 5.0 on 2023-12-21 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_posts_created_at_posts_date_posts_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='url',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
